# Generated by Django 3.2.18 on 2024-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Medium', max_length=100),
            preserve_default=False,
        ),
    ]
