# Generated by Django 3.2.18 on 2024-05-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
